# Servicios de almacenamiento de datos
# Desarrollo
services:
  # PostgreSQL
  postgres-db:
    container_name: funkos-db_postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - funkos-network

networks:
  funkos-network:
    driver: bridge